const Constants = {
  ScreenTitles: {
    SHOP: 'Shop',
    SHOPCART: 'Cart',
    HOME: 'Home',
    PRODUCTSlist: 'productsList',
    ADDRESS: 'Address',
  },
  ButtonTitle: {
    ADDITEM: 'Add Item',
    ADDED: 'Item Added',
    ADDTOCART: 'Add to Cart',
    ADDRESS: 'Add Address',
    SAVE: 'SAVE',
    CANCEL: 'CANCEL',
    HOME: 'Home',
    WORK: 'Work',
  },
  Title: {
    HOMEDECOR: 'Home Decor',
    ELECTRONICS: 'Electronics',
    SHOES: 'Shoes',
    DAILYUSE: 'Daily Use',
    COSMETICS: 'Cosmetics',
    ADDRESSTITLE: 'Add Address',
    ADDRESSTEXT: 'Please add your address',
    ADDRESSTYPE: 'Address type',
  },
  TitleTextField: {
    FULLNAME: 'Full Name',
    MOBILE: 'Mobile',
    PINCODE: 'Pincode',
    LOCALITY: 'Locality',
    ADDRESS: 'Address',
    CITY: 'City',
    STATE: 'State',
    LANDMARK: 'Landmark',
    ALTERNATE: 'Alternate Phone Number',
  },
  Placeholder: {
    ENTERNAME: 'Full Name',
    ENTERMOBILE: '10 - Digit Mobile Number',
    ENTERPINCODE: 'Pincode',
    ENTERLOCALITY: 'Locality',
    ENTERADDRESS: 'Address (Area and Street)',
    ENTERCITY: 'City/District/Town',
    ENTERSTATE: 'Enter State',
    ENTERLANDMARK: 'Landmark',
    ENTERALTERNATE: 'Alternate Phone Number (Optional)',
  },
  SUB_CATEGORIES: {
    BEDSHEETS: 'Bed Sheets',
    CURTAINS: 'Curtains',
    PAINTINGS: 'Paintings',
    PILLOWS: 'Pillows',
    SOFAS: 'Sofas',
    AC: 'AC',
    LAPTOPS: 'Laptops',
    MICROWAVE: 'Microwave',
    PHONE: 'Phones',
    REFRIGERATORS: 'Refrigerator',
    WASHINGMACHINES: 'Washing Machine',
    BOOTS: 'Boots',
    HEELS: 'Heels',
    SLIPPERS: 'Slippers',
    SNEAKERS: 'Sneakers',
    BAGS: 'Bags',
    SANITIZERS: 'Sanitizers',
    SHAMPOO: 'Shampoo',
    TOWEL: 'Towels',
    WATCH: 'Watches',
    WATERBOTTLE: 'Water Bottles',
    LIPSTICKS: 'Lipsticks',
    MAKEUP: 'Makeup Pallates',
  },
  MESSAGES: {
    NODATA: 'No Items Available',
    WELCOME: 'Welcome',
  },
  ALERT: {
    AlertOnDelete: 'Your item will get deleted from Cart.',
    AlertOnRemove: 'Your item will get removed from Wishlist.',
  },
  TOASTTEXTS: {
    PASSWORD: 'Password should have minimum 8 characters',
    CONTACT: 'Contact should be of 10 digits',
    SAVEADDRESS: 'Address Saved',
    PINCODE: 'Invalid Pincode',
    NAME: 'Enter Name',
    LOCALITY: 'Locality',
    ADDRESS: 'Enter Address',
    CITY: 'Enter City',
    LANDMARK: 'Landmark',
  },
};
export default Constants;
